name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install zig
        env:
          URL: https://ziglang.org/builds/zig-bootstrap-0.16.0-dev.747+493ad58ff.tar.xz
        run: |
          curl -L $URL -o zig.tar.xz
          tar -xf zig.tar.xz
          sudo mv zig-* /opt/zig
          echo "/opt/zig" >> $GITHUB_PATH

      - name: Run ci.json
        run: zig build run -Drelease-safe -- ci.json
