name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install zig
        env:
          URL: https://ziglang.org/builds/zig-bootstrap-0.16.0-dev.747+493ad58ff.tar.xz
        run: |
          echo "Installing zig from $URL"
          curl -L $URL -o zig.tar.xz
          echo "Extracting zig"
          tar -xf zig.tar.xz
          mv zig-* /opt/zig
          ls -la /opt/zig
          echo "Adding zig to PATH"
          echo "/opt/zig/zig" >> $GITHUB_PATH

      - name: Run ci.json
        run: |
          echo $PATH
          zig build run -Drelease-safe -- ci.json
